whatSticksWebApp/main/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, abort, session,\
    Response, current_app, send_from_directory
from whatSticksWebApp import db, bcrypt, mail
from whatSticksWebApp.models import Users, Posts, Health_descriptions, Polar_descriptions, Polar_measures,\
    Oura_sleep_descriptions, Oura_sleep_measures
from flask_login import login_user, current_user, logout_user, login_required
import secrets
import os
from datetime import datetime, date, time, timedelta
import datetime
from sqlalchemy import func, desc
import pandas as pd
import json
import zipfile
from whatSticksWebApp.main.utils import get_user_tz_util
# from bokeh.plotting import figure, output_file
# from bokeh.embed import components
from bokeh.resources import CDN
# from bokeh.io import curdoc
# from bokeh.themes import built_in_themes
# from bokeh.models import ColumnDataSource, Grid, LinearAxis, Plot, Text
import pytz
import zoneinfo
from pytz import timezone
import time
import requests
from whatSticksWebApp.main.utilsOura import link_oura
from whatSticksWebApp.main.utilsDashTableData import data_dfs, user_activity_list, polar_list,\
    oura_sleep_list, leading_zeros_count
from whatSticksWebApp.main.utilsPolarUpload import json_dict_to_dfs
from whatSticksWebApp.utilsDecorator import nav_add_data
from whatSticksWebApp.utils import logs_dir
from whatSticksWebApp.main.utilsCharts import polar_chart_params, user_act_chart_params,\
    user_wgt_chart_params, oura_sleep_chart_params,chart_bokeh_obj
from whatSticksWebApp.main.utilsChartsDash import polar_bar_chart_dash, oura_sleep_bar_chart_dash
import logging
from logging.handlers import RotatingFileHandler


# #Setting up Logger
formatter = logging.Formatter('%(asctime)s:%(name)s:%(message)s')
formatter_terminal = logging.Formatter('%(asctime)s:%(filename)s:%(name)s:%(message)s')

logger_main = logging.getLogger(__name__)
logger_main.setLevel(logging.DEBUG)
# logger_terminal = logging.getLogger('terminal logger')
# logger_terminal.setLevel(logging.DEBUG)

file_handler = RotatingFileHandler(os.path.join(logs_dir,'main.log'), mode='a', maxBytes=5*1024*1024,backupCount=2)
file_handler.setFormatter(formatter)

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(formatter_terminal)

# logger_terminal.handlers.clear()
logger_main.addHandler(file_handler)
logger_main.addHandler(stream_handler)

# #End set up logger


main = Blueprint('main', __name__)



@main.route("/about", methods=["GET","POST"])
# @nav_add_data
def about(**kwargs):#<-- must have **kwargs with @nav_add_data
    logger_main.info(f'***In about page***')
    default_date=kwargs.get('default_date')
    default_time=kwargs.get('default_time')
    return render_template('about.html',**kwargs)

@main.route("/privacy", methods=["GET","POST"])
# @nav_add_data
def privacy(**kwargs):#<-- must have **kwargs with @nav_add_data
    default_date=kwargs.get('default_date')
    default_time=kwargs.get('default_time')
    return render_template('privacyStatement.html',**kwargs)

@main.route("/contactus", methods=["GET","POST"])
# @nav_add_data
def contactus(**kwargs):#<-- must have **kwargs with @nav_add_data
    default_date=kwargs.get('default_date')
    default_time=kwargs.get('default_time')
    return render_template('contactUs.html',**kwargs)

@main.route("/dashboard", methods=["GET","POST"])
@nav_add_data
@login_required
def dashboard(**kwargs):
    
    default_date=kwargs['default_date']
    default_time=kwargs['default_time']

    #data_dfs is a dictionary of DataFrames for each descriptions db.
    # df_health_descriptions,df_polar_descriptions,df_oura_sleep_descriptions = data_dfs()
    df_dict=data_dfs()

    #Make flags for at_least_one_record_hd, at_least_one_record_polar, at_least_one_record_oura_sleep
    at_least_one_record_hd=False
    at_least_one_record_polar=False
    at_least_one_record_oura_sleep=False
    no_hits_flag=False
    
    for i,j in df_dict['df_health_descriptions'].items():
        if len(j)>0:
            at_least_one_record_hd=True
    for i,j in df_dict['df_polar_descriptions'].items():
        if len(j)>0:
            at_least_one_record_polar=True    
    for i,j in df_dict['df_oura_sleep_descriptions'].items():
        if len(j)>0:
            at_least_one_record_oura_sleep=True


    #Timleline table columns
    column_names=['ID','Date and Time','Activity','Duration', 'Rating']
    #Timeline table list
    table_lists=[]

    current_endpoint=request.url_rule.endpoint

    if at_least_one_record_hd:
        table_lists=user_activity_list(df_dict['df_health_descriptions'])

    if at_least_one_record_polar:
        # script1, div1=chart_bokeh_obj(df_dict['df_polar_descriptions'])
        script1, div1, text_detail_dashed_lines=polar_bar_chart_dash()
        table_lists=table_lists+polar_list(df_dict['df_polar_descriptions'])
        cdn_js=CDN.js_files
        cdn_css=CDN.css_files
    else:
        div1=None;script1=None;cdn_js=None;cdn_css=None;text_detail_dashed_lines=None


    if at_least_one_record_oura_sleep:
        print('at_least_one_record_oura_sleep::: TRUE')
        script_oura_sleep, div_oura_sleep, oura_sleep_text_detail_dashed_lines=oura_sleep_bar_chart_dash()
        table_lists=table_lists+oura_sleep_list(df_dict['df_oura_sleep_descriptions'])
        # print('oura_sleep_text_detail_dashed_lines::',oura_sleep_text_detail_dashed_lines)
        cdn_js=CDN.js_files
        cdn_css=CDN.css_files
    else:
        script_oura_sleep=None;div_oura_sleep=None;oura_sleep_text_detail_dashed_lines=None
        print('at_least_one_record_oura_sleep::: FALSE')


        # if len(df_dict['df_health_descriptions'])>0:
        #     table_lists=user_activity_list(df_dict['df_health_descriptions'])
        # if len(df_dict['df_polar_descriptions'])>0:
        #     table_lists=table_lists+polar_list(df_dict['df_polar_descriptions'])
        # if len(df_dict['df_oura_sleep_descriptions'])>0:
        #     table_lists=table_lists+oura_sleep_list(df_dict['df_oura_sleep_descriptions'])
        
        # no_hits_flag=True if len(table_lists)==0 else False
    if len(table_lists) == 0:
        #vars for chart that doesn't exist
        # div1=None;script1=None;cdn_js=None;cdn_css=None;text_detail_dashed_lines=None
        # script_oura_sleep=None;div_oura_sleep=None;oura_sleep_text_detail_dashed_lines=None
        #vars for dataframe that doesn't exist:
        # table_lists=None
        no_hits_flag=True
        column_names=None



    if request.method == 'POST':
        formDict = request.form.to_dict()
        logger_main.info(f'dashboard--post formDict::: {formDict}')
        if formDict.get('submit_upload_health')=='True':
            return redirect(url_for('main.upload_health_data'))
        elif formDict.get('delete_record_id'):
            return redirect(url_for('main.delete_record',current_endpoint=current_endpoint,
                delete_record_id=formDict.get('delete_record_id')))

    return render_template('dashboard.html', div1=div1, script1=script1, cdn_js=cdn_js, cdn_css=cdn_css,
        default_date=default_date, default_time=default_time,table_data=table_lists,
        no_hits_flag=no_hits_flag,len=len,column_names=column_names, text_detail_dashed_lines=text_detail_dashed_lines,
        script_oura_sleep= script_oura_sleep, div_oura_sleep= div_oura_sleep,
        oura_sleep_text_detail_dashed_lines=oura_sleep_text_detail_dashed_lines)


@main.route("/for_scientists", methods=["GET","POST"])
@nav_add_data
@login_required
def for_scientists(**kwargs):
    # logger_main.info(f'for_scientists--requests::: {request.args}')
    print('*** ENTER for_analysis ****')
    default_date=kwargs['default_date']
    default_time=kwargs['default_time']
    df_dict=data_dfs()

    # print(df_dict['df_health_descriptions'])

    at_least_one_record = False

    current_endpoint=request.url_rule.endpoint

    chart_params_dict={}

    if len(df_dict['df_health_descriptions']) > 0:
        #get user_act params
        chart_params_dict['user_act']=user_act_chart_params(df_dict['df_health_descriptions'])
        #get weight params
        chart_params_dict['user_wgt']=user_wgt_chart_params(df_dict['df_health_descriptions'])
        print('^^^^^ THING of INTEREST ^^^^^')
        print(chart_params_dict['user_wgt'])
        
        if chart_params_dict.get('user_act'):
            max_date = max(chart_params_dict['user_act'][0])

        if chart_params_dict.get('user_wgt'):
            print('chart_params_dict.get(user_wgt):::', chart_params_dict.get('user_wgt'))
            if max(chart_params_dict['user_wgt'][0]) > max_date:
                max_date = max(chart_params_dict['user_wgt'][0])
        
        # at_least_one_record_hd = True
        at_least_one_record = True
        

    if len(df_dict['df_polar_descriptions']) > 0:
        #get polar_chart params
        chart_params_dict['polar']=polar_chart_params(df_dict['df_polar_descriptions'])
        if max(chart_params_dict['polar'][0]) > max_date:
            max_date = max(chart_params_dict['polar'][0])
        
        at_least_one_record = True

    if len(df_dict['df_oura_sleep_descriptions']) > 0:
        #get oura_sleep params
        chart_params_dict['oura_sleep']=oura_sleep_chart_params(df_dict['df_oura_sleep_descriptions'])
        if max(chart_params_dict['oura_sleep'][0]) > max_date:
            max_date = max(chart_params_dict['oura_sleep'][0])
        
        at_least_one_record = True

    #based on max date of all data make the default view max day to -timedelta(days=7)

    if at_least_one_record:
        print('at_least_one_record ::: True')

        #get chart start and end date based on gathered params
        chart_params_dict['chart']=[max_date -timedelta(days=7),max_date+ timedelta(days=7)]
        
        #get script1 and div1 objs using params

        script1, div1=chart_bokeh_obj(chart_params_dict)
        # print('***********************')

whatSticksWebApp/templates/about.html
    {% extends "layout.html" %}
    {% block title %} About WSH {% endblock %}
    {% block main %}
<section class="About">
    <div class="container">

        <h1>About Us</h1>
        <div class="mission_div">
            <div class="sectionWriting">
                <h1>Mission</h1>
                Build an easy to use and transparent data storage platform that provides insights on lifestyle areas (physical, mental and social) that are specific to users.<br/><br/>

            </div>
        </div>
<br/><br/>


<div class="mission_div">
    <div class="sectionWriting">
        <h1>Mission (Layman's Terms)</h1>
        WSH aims to leverage technology used by <b>social media</b> companies to collect data to build a data repository that can be used to give users personalized feedback on their life style instead of selling them stuff.<br/><br/>

        One questions many of us frequently asking myself is why we have more energy some days than others. An Oura ring tells you that you didn’t sleep well. Ok, well you probably already knew that. But why didn’t you sleep well. What were some of the factors that contributed to that and are they avoidable?  Some might be obvious, but others might not be as much.<br/><br/>

        Leveraging technology used by existing technology/social media companies, wearables and other sources WSH aims to build platform that will offer users transparent control of their data and provide feedback that will improve quality of life across all aspects of life – physical, mental and social.<br/><br/>
    </div>
</div>
<br/><br/>


        <div class="mission_div">
            <div class="sectionWriting">
                <h1>Vision</h1>
                What Sticks Health (WSH) is a health data storage infrastructure that provides personalized feedback. It is a work in progress. You can visit it at https://what-sticks-health.com to see what is there so far but here is a breakdown of what is going on.
                If you think you can help feel free to reach out.<br/><br/>

                <h2>Existing Platform</h2>
                <ul>
                    <li>
                        Data Storage: web application that allows users to upload Polar Beat training session, weight and user specified activity ( i.e. drinking coffee, headache, emotion, etc.,)
                    </li>
                    <li>
                        Feedback: Polar Beat training session indexed to model for cardio health
                    </li>
                </ul>
                <h2>Next Steps (Immediate)</h2>
                <ul>
                    <li>Data Storage: iOS and Android device application (weight and activity) https://github.com/costa-rica/whatSticksKivy09</li>
                    <li>Feedback: build correlations to provide simple feedback — similar to the training session heart rate modeling</li>
                </ul>
                <h2>Next Steps (Near Future)</h2>
                <ul>
                    <li>Encrypted data storage</li>
                    <li>Anonymized data</li>
                    <li>Interoperability to upload and share data</li>
                    <li>Build more in platform feedback</li>
                    <li>Include well established health benchmarks to assist user feedback</li>
                </ul>
                
            </div>
        </div>

        <br/><br/>
        <div class="mission_div">
            <div class="sectionWriting">
                <h1>Why?</h1>
        <a href="https://nrodrig1.medium.com/healthcare-is-not-up-to-date-2e58c01c1477">Healthcare is Not Up-To-Date</a>
        </div>
    </div>
    </div>

</section>

{% endblock %}

whatSticksWebApp/templates/home.html
    {% extends "layoutHome.html" %}
    {% block title %} WSH Home {% endblock %}
    {% block main %}
<section class="Home">
    <div class="container">

        <h1>Welcome</h1>
        <div class="home_link_list_div">
            <ul class="home_link_list">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>                
                <li><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
                    {% if current_user.username!='Guest' %}
                    <li><a href="{{ url_for('users.account') }}">Account</a></li>
                    {% endif %}
                
                {% else %}
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>


    </div>
</section>

{% endblock %}

whatSticksWebApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Import our custom stylesheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <!-- Bootstrap5 css -->
    <link rel="stylesheet" type="text/css" href="../static/bootstrap/css/dataTables.bootstrap5.min.css">

    <!--Modal scripts (nav drpdown)-->
    <script src="../static/bootstrap/js/bootstrap.min.js"></script>
    <!-- Tables seem to need these -->
    <script src="../static/bootstrap/table_version/jquery-3.5.1.js"></script>
    <script src="../static/bootstrap/table_version/jquery.dataTables.min.js"></script>
    <script src="../static/bootstrap/table_version/dataTables.bootstrap.min.js"></script>
    <script src="../static/bootstrap/js/dataTables.bootstrap5.min.js"></script>


    <!-- Datatable ---- ****KEEP**** commented links for reference-->
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css"> -->
    <link rel="stylesheet" type="text/css" href="../static/bootstrap/css/jquery.dataTables.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css"> -->
    <link rel="stylesheet" type="text/css" href="../static/bootstrap/css/responsive.dataTables.min.css">
    <!-- <script type = "text/javascript"  src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script> -->
    <script type = "text/javascript" src="../static/bootstrap/js/jquery.dataTables.min.js"></script>
    <!-- <script type = "text/javascript"  src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script> -->
    <script type = "text/javascript" src="../static/bootstrap/js/dataTables.responsive.min.js"></script>




    <title>{% block title %}{% endblock %}</title>
</head>


{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <br/><br/><br/><br/><br/><br/>
  {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
{% endwith %}



<body>
    <!-- <nav class="navbar navbar-expand-lg bg-primary"> -->
    <div class="navbar fixed-top  navbar-light bg-light"> 

        <div class="custom_container">
            <div class="">
                <a href="{{ url_for('users.home') }}" class="custom_link">
                    <!-- <div class="text_center"> -->
                        <img class="custom_logo_nav " src="../static/images/wshLogo_test300px.png" alt="LB logo">
                        <span class="company_name">What Sticks</span>
                    <!-- </div> -->
                </a>
            </div>


            
            <div class="middle_nav_div">
                {% if current_user.is_authenticated %}
                <h2>{{ current_user.username }}</h2>
                <!-- <small>(is currently signed in)</small> -->
                {% endif %}
            </div>

            <!-- Hamburger bars -->
            <img class="mobile-menu" id="mobile-cta" src="../static/images/menu.svg" alt="Open Navigation">

            <nav>
                <img id="mobile-exit" class="mobile-menu-exit" src="../static/images/exit.svg" alt="Close Navigation">
                <ul class="primary-nav ul_primary" id="nav_horizontal_list">
                    {% if current_user.is_authenticated %}
                                       
                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown1"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">Your Data</a>

                            <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown1">
                                <a class="dropdown-item" href="{{ url_for('main.dashboard') }}">Dashboard</a>
                                <a class="dropdown-item" href="{{ url_for('main.upload_health_data') }}">Link/Add Device</a>

                                <button type="button" class="button_link" data-bs-toggle="modal" 
                                    data-bs-target="#activityModal">Add Activity
                                </button>
                                <button type="button" class="button_link" data-bs-toggle="modal" 
                                data-bs-target="#weightModal">Add Weight
                                </button>
                                <a class="dropdown-item grey_background" href="{{ url_for('main.for_scientists') }}">Analysis</a>
                            </div>
                    </li>
                    
                    <!-- <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('main.about') }}">About</a></li> -->

                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">About</a>

                            <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{{ url_for('main.about') }}">About</a>
                                <a class="dropdown-item" href="{{ url_for('main.privacy') }}">Privacy</a>
                                <a class="dropdown-item" href="{{ url_for('main.contactus') }}">Contact Us</a>
                            </div>
                    </li>


                    <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}

                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">About</a>

                            <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{{ url_for('main.about') }}">About</a>
                                <a class="dropdown-item" href="{{ url_for('main.privacy') }}">Privacy</a>
                                <a class="dropdown-item" href="{{ url_for('main.contactus') }}">Contact Us</a>
                            </div>
                    </li>


                    <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>




        </div>
    </div>
    

    <form method="POST" action="" enctype="multipart/form-data">
        <!-- Modal -->
          <div class="modal fade" id="activityModal" tabindex="-1" aria-labelledby="activityModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content ">
                <div class="modal-header modal_header_add">
                  <h5 class="modal-title" id="activityModalLabel">Enter Activity</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body modal_body_add">
                    <div class="enter_activity_sub">
                        <div>
                            <label>Date:</label>
                            <input type="date" value="{{ default_date }}" name="activity_date">
                            <label>Time:</label>
                            <input type="time" value="{{ default_time }}" name="activity_time">
                        </div>
                        <div class="enter_activity_sub2">
                            <label>Activity:</label>
                            <input type="text" placeholder="required (30 char max)" name="var_activity">
                        </div>
                        <div class="enter_activity_sub2">
                            <label>Activity Notes:</label>
                            <textarea  name="activity_notes" rows=2  placeholder="optional"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer modal_body_add">
                    <button type="submit" class="btn btn-primary" name="submit_activity" value=True>
                        Submit Activity
                    </button>
                </div>
              </div>
            </div>
          </div>
        </form>

        
        <form method="POST" action="" enctype="multipart/form-data">
            <!-- Modal Weight -->
                <div class="modal fade" id="weightModal" tabindex="-1" aria-labelledby="weightModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                    <div class="modal-content ">
                        <div class="modal-header modal_header_add">
                        <h5 class="modal-title" id="weightModalLabel">Enter Weight</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body modal_body_add">
                            <div class="enter_activity_sub">
                                <div>
                                    <label>Date:</label>
                                    <input type="date" value="{{ default_date }}" name="activity_date">
                                    <label>Time:</label>
                                    <input type="time" value="{{ default_time }}" name="activity_time">
                                </div>
                                <div class="enter_activity_sub2">
                                    <label>Weight (lbs):</label>
                                    <input type="text" name="weight_input">
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer modal_body_add">
                            <button type="submit" class="btn btn-primary" name="submit_weight" value=True>
                                Submit Activity
                            </button>
                        </div>
                    </div>
                    </div>
                </div>
            </form>

    {% block main %}{% endblock %}




	{% block script %}{% endblock %}
    <script>
        const mobileBtn = document.getElementById('mobile-cta')
            nav = document.querySelector('nav')
            mobileBtnExit = document.getElementById('mobile-exit');

      mobileBtn.addEventListener('click', () => {
          nav.classList.add('menu-btn');
      })

      mobileBtnExit.addEventListener('click', () => {
          nav.classList.remove('menu-btn');
      })
</script>

</body>
</html>

whatSticksWebApp/templates/layoutHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Import our custom stylesheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <!-- Bootstrap5 css -->
    <link rel="stylesheet" type="text/css" href="../static/bootstrap/css/dataTables.bootstrap5.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="../static/bootstrap/table_version20211220/dataTables.bootstrap4.min.css"> -->
    <!--Modal scripts (nav drpdown)-->
    <script src="../static/bootstrap/js/bootstrap.min.js"></script>
    <!-- Tables seem to need these -->
    <script src="../static/bootstrap/table_version/jquery-3.5.1.js"></script>
    <script src="../static/bootstrap/table_version/jquery.dataTables.min.js"></script>
    <script src="../static/bootstrap/table_version/dataTables.bootstrap.min.js"></script>
    <script src="../static/bootstrap/js/dataTables.bootstrap5.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
</head>


{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <br/><br/><br/><br/><br/><br/>
  {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
{% endwith %}



<body>
    <!-- <nav class="navbar navbar-expand-lg bg-primary"> -->
    <div class="navbar fixed-top  navbar-light bg-light"> 

        <div class="custom_container">
            <div class="nowrap_containter">
                <a href="{{ url_for('users.home') }}" class="custom_link">
                    <!-- <div class="text_center"> -->
                        <img class="custom_logo_nav " src="../static/images/wshLogo_test300px.png" alt="LB logo">
                        <span class="company_name">What Sticks</span>
                    <!-- </div> -->
                </a>
            </div>


            
            <div class="middle_nav_div">
                {% if current_user.is_authenticated %}
                <h2>{{ current_user.username }}</h2>
                <!-- <small>(is currently signed in)</small> -->
                {% endif %}
            </div>


            <img class="mobile-menu" id="mobile-cta" src="../static/images/menu.svg" alt="Open Navigation">

            <nav>
                <img id="mobile-exit" class="mobile-menu-exit" src="../static/images/exit.svg" alt="Close Navigation">
                <ul class="primary-nav ul_primary" id="nav_horizontal_list">
                    {% if current_user.is_authenticated %}
                                       
                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">Your Data</a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('main.dashboard') }}">Dashboard</a>

                                <a class="dropdown-item grey_background" href="{{ url_for('main.for_scientists') }}">Analysis</a>
                            </div>
                    </li>
                    
                    <!-- <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('main.about') }}">About</a></li> -->
                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">About</a>

                            <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{{ url_for('main.about') }}">About</a>
                                <a class="dropdown-item" href="{{ url_for('main.privacy') }}">Privacy</a>
                                <a class="dropdown-item" href="{{ url_for('main.contactus') }}">Contact Us</a>
                            </div>
                    </li>
                    <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                    <li class="nav-item dropdown li_primary">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                            data-bs-toggle="dropdown"aria-expanded="false">About</a>

                            <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{{ url_for('main.about') }}">About</a>
                                <a class="dropdown-item" href="{{ url_for('main.privacy') }}">Privacy</a>
                                <a class="dropdown-item" href="{{ url_for('main.contactus') }}">Contact Us</a>
                            </div>
                    </li>
                    <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>




        </div>
    </div>
    


    {% block main %}{% endblock %}




	{% block script %}{% endblock %}
    <script>
        const mobileBtn = document.getElementById('mobile-cta')
            nav = document.querySelector('nav')
            mobileBtnExit = document.getElementById('mobile-exit');

      mobileBtn.addEventListener('click', () => {
          nav.classList.add('menu-btn');
      })

      mobileBtnExit.addEventListener('click', () => {
          nav.classList.remove('menu-btn');
      })
</script>

</body>
</html>